<SerialTestWindow>:    
    Label:
        text: "TSU Rover Ground Station"
        font_size: 100
        font_name: 'Dodger'
        size_hint: None, None
        pos: root.center_x, root.height - 200
    Button: 
        text: "Return Serialport List"
        font_size: 40
        font_name: 'Roboto'
        color: (1,0,0,1)
        background_color: (1,1,0,1)
        background_normal: ''
        size_hint: None, None
        size: self.texture_size
        pos: (root.center_x-1400,root.height - 300)
        on_release: root.port_list()  
    Label:
        id: l2
        text: "Serial List"
        font_size: 40
        size_hint: None, None
        multiline: True
        size: self.texture_size
        color: (1,1,1,1)
        pos: (root.center_x-1400,root.height - 400)
    Button: 
        text: "Input Serialport Address"
        font_size: 40
        font_name: 'Roboto'
        color: (1,0,0,1)
        background_color: (1,1,0,1)
        background_normal: ''
        size_hint: None, None
        size: self.texture_size
        pos: (root.center_x-1400,root.height - 530)
        on_release: root.got_port()        
    TextInput:
        id: l4
        text: "Input Serialport Address\n Example: /dev/cu.usbmodem1421"   
        multiline: True 
        font_size: 40
        size_hint: None, None
        size: 800,120   
        color: (0,0,0,1)
        background_color: (1,1,1,1)
        background_normal: ''    
        pos: (root.center_x-900,root.height - 580)    
            
    Button: 
        text: "Try Serial Connection"
        font_size: 40
        font_name: 'Roboto'
        color: (1,0,0,1)
        background_color: (1,1,0,1)
        background_normal: ''
        size_hint: None, None
        size: self.texture_size
        pos: (root.center_x -50,root.height - 530)
        on_release: root.port_cont()  
    Label:
        id: l3
        text: "Serial Connection"
        font_size: 40
        size_hint: None, None
        color: (1,1,1,1)
        pos: (root.center_x +100,root.height - 630)
    Button: 
        text: "Try Joystick Connection"
        font_size: 40
        font_name: 'Roboto'
        color: (1,0,0,1)
        background_color: (1,1,0,1)
        background_normal: ''
        size_hint: None, None
        size: self.texture_size
        pos: (root.center_x-1400, root.height - 700)
        on_release: root.got_joystick() 
    Label:
        id: l5
        text: "Joystick Output"
        multiline: True    
        font_size: 40
        size_hint: None, None
        size: self.texture_size    
        color: (1,1,1,1)
        pos: (root.center_x-800,root.height - 850) 
    Button: 
        text: "Start Streaming Data from Arduino"
        font_size: 40
        font_name: 'Roboto'
        color: (1,0,0,1)
        background_color: (1,1,0,1)
        background_normal: ''
        size_hint: None, None
        size: self.texture_size
        pos: (root.center_x-1400,root.height - 930)
        on_release: root.got_data() 
    Label:
        id: l6
        text: "Arduino Serial Not Streaming"
        font_size: 40
        size_hint: None, None
        color: (1,1,1,1)
        pos: (root.center_x-400,root.height - 960) 
    Label:
        id: l7
        text: "Incoming Data Stream"
        font_size: 40
        size_hint: None, None
        size: self.texture_size
        color: (1,1,1,1)
        pos: (root.center_x-1400,root.height - 1100) 
    Label:
        id: l9
        text: "Data"
        font_size: 40
        size_hint: None, None
        size: self.texture_size
        color: (1,1,1,1)
        pos: (root.center_x-800,root.height - 1100)     
    Label:
        id: l8
        text: "Outgoing Data Stream"
        font_size: 40
        size_hint: None, None
        size: self.texture_size
        color: (1,1,1,1)
        pos: (root.center_x-1400,root.height - 1300)
    Label:
        id: l10
        text: "Data"
        font_size: 40
        size_hint: None, None
        size: self.texture_size
        color: (1,1,1,1)
        pos: (root.center_x-800,root.height - 1300)     
    Button: 
        text: "Terminate Window"
        font_size: 40
        font_name: 'Roboto'
        color: (1,0,0,1)
        background_color: (1,1,0,1)
        background_normal: ''
        size_hint: None, None
        size: self.texture_size
        pos: (root.center_x-1400,root.height - 200)
        on_release: root.term()     
    Label:
        id: l11
        text: "input buffer size"
        font_size: 40
        size_hint: None, None
        size: self.texture_size
        color: (1,1,1,1)
        pos: (root.center_x-300,root.height - 1100)
    Label:
        id: l12
        text: "output buffer size"
        font_size: 40
        size_hint: None, None
        size: self.texture_size
        color: (1,1,1,1)
        pos: (root.center_x-300,root.height - 1300)    
            
           
        
            
  
   